theme: minima
title: GitHub pages by Nicole Paucar
author: Nicole Paucar
description: This is my first time using GitHub pages and I don't know what I am doing to a 100% YET. Bear with me while I learn how to use this :smile:.
